Missing for loop variable 'j' initializor.
Fixed the following error

[ 15%] Building C object nva/CMakeFiles/nva.dir/nva.c.o
/home/tomwij/envytools/nva/nva.c: In function ‘nva_init’:
/home/tomwij/envytools/nva/nva.c:105:9: error: ‘j’ undeclared (first use in this function)
/home/tomwij/envytools/nva/nva.c:105:9: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [nva/CMakeFiles/nva.dir/nva.c.o] Error 1
make[1]: *** [nva/CMakeFiles/nva.dir/all] Error 2
make: *** [all] Error 2

by adding `int j;` before the for loop on line 105.